// const baseUrl = "http://10.2.44.52:8888/api";
export const baseUrl = "http://localhost:8888/api";
export const SENDMESSAGE = `${baseUrl}/message/send-message`;
export const INFOUSER = `${baseUrl}/user/info`;
export const LISTUSER = `${baseUrl}/message/list-friend`;
export const UPDATEUSER = `${baseUrl}/api/user/update`;
export const LOGIN = `${baseUrl}/auth/login`;
export const REGISTER = `${baseUrl}/auth/register`;
export default baseUrl;
SENDMESSAGE;
INFOUSER;
LISTUSER;
UPDATEUSER;
LOGIN;
REGISTER;
